databases:
  - name: rails-render-demo
    databaseName: rails-render-demo
    user: rails-render-demo

services:
  - type: web
    name: rails-render-demo
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-render-demo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
